pipeline {
    agen any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Nashat-Ahmed/simpleCI-CD.git'  
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t nashaat111/webapp:v.0 .'
                }
            }
        }
        stage('Login to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', nashaat111) {
                        echo 'Logged in to Docker Hub'
                    }
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh 'docker push nashaat111/wepapp:v.0'
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
