pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    def image = docker.build("nashaat111/webapp:v0")
                    image.push()
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'kubectl apply -f deployment.yml'
            }
        }
    }
}

